# Generated by Django 4.2.30 on 2026-07-30 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registration",
            options={"ordering": ["-registered_at", "-id"]},
        ),
    ]
