# Generated by Django 4.2.30 on 2026-07-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0003_alter_registration_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Approved",
                max_length=50,
            ),
        ),
    ]
