# Generated by Django 4.2.30 on 2026-08-04 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hackathons", "0003_hackathon_publish_time"),
        ("registrations", "0004_alter_registration_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodCoupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("Lunch", "Lunch"),
                            ("Dinner", "Dinner"),
                            ("Breakfast", "Breakfast"),
                            ("Snack", "Snack"),
                            ("Special", "Special VIP"),
                        ],
                        default="Lunch",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("meal_date", models.DateField(blank=True, null=True)),
                ("default_coupons_per_person", models.PositiveIntegerField(default=1)),
                ("target_roles", models.CharField(default="All", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hackathon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_coupons",
                        to="hackathons.hackathon",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserFoodToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token_code",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("total_coupons", models.PositiveIntegerField(default=1)),
                ("used_coupons", models.PositiveIntegerField(default=0)),
                ("is_extra", models.BooleanField(default=False)),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("last_scanned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "food_coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_tokens",
                        to="registrations.foodcoupon",
                    ),
                ),
                (
                    "hackathon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_food_tokens",
                        to="hackathons.hackathon",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FoodRedemptionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("redeemed_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="Success", max_length=50)),
                (
                    "scanned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scanned_food_redemptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemption_logs",
                        to="registrations.userfoodtoken",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="userfoodtoken",
            constraint=models.UniqueConstraint(
                fields=("food_coupon", "user"), name="unique_user_food_coupon"
            ),
        ),
    ]
