# Generated by Django 4.2.30 on 2026-07-28 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hackathons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HackathonMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Organizer", "Organizer"),
                            ("Volunteer", "Volunteer"),
                            ("Judge", "Judge"),
                            ("Mentor", "Mentor"),
                            ("Participant", "Participant"),
                        ],
                        max_length=50,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invitation_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Accepted", "Accepted"),
                            ("Rejected", "Rejected"),
                            ("Removed", "Removed"),
                        ],
                        default="Pending",
                        max_length=50,
                    ),
                ),
                (
                    "hackathon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="hackathons.hackathon",
                    ),
                ),
            ],
        ),
    ]
