# Generated by Django 4.2.30 on 2026-08-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackathons", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hackathon",
            name="publish_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
