# Generated by Django 4.2.30 on 2026-08-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackathons", "0004_hackathontitle"),
    ]

    operations = [
        migrations.AddField(
            model_name="hackathon",
            name="is_problem_statements_released",
            field=models.BooleanField(default=False),
        ),
    ]
