# Generated by Django 4.2.30 on 2026-07-28 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hackathons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("design_score", models.IntegerField(default=0)),
                ("execution_score", models.IntegerField(default=0)),
                ("innovation_score", models.IntegerField(default=0)),
                ("presentation_score", models.IntegerField(default=0)),
                ("feedback", models.TextField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now=True)),
                (
                    "hackathon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="hackathons.hackathon",
                    ),
                ),
            ],
        ),
    ]
