# Generated by Django 4.2.30 on 2026-07-28 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hackathons", "0001_initial"),
        ("announcements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduleitem",
            name="hackathon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule_items",
                to="hackathons.hackathon",
            ),
        ),
        migrations.AddField(
            model_name="rule",
            name="hackathon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rules",
                to="hackathons.hackathon",
            ),
        ),
    ]
