# Generated by Django 4.2.30 on 2026-07-28 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hackathons", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("announcements", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="announcements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="hackathon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="announcements",
                to="hackathons.hackathon",
            ),
        ),
    ]
