# Generated by Django 4.2.30 on 2026-07-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Submitted", "Submitted"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
    ]
