# Generated by Django 4.2.30 on 2026-08-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0004_teamjoinrequest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="invite_code",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
