# Generated by Django 4.2.30 on 2026-08-02 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0006_teamchatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamchatmessage",
            name="is_edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="teamchatmessage",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="teams.teamchatmessage",
            ),
        ),
        migrations.AddField(
            model_name="teamchatmessage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
