# Generated by Django 4.2.30 on 2026-08-02 08:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teams", "0007_teamchatmessage_is_edited_teamchatmessage_reply_to_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamchatmessage",
            name="seen_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="seen_chat_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
