# Generated by Django 4.2.30 on 2026-08-05 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hackathons", "0004_hackathontitle"),
        ("teams", "0008_teamchatmessage_seen_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="selected_title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="selected_by_teams",
                to="hackathons.hackathontitle",
            ),
        ),
    ]
